services:
    users:
      build:
        context: ./users
        dockerfile: ./Dockerfile
      command: >
              sh -c "php artisan config:clear
              && php artisan serve --host=0.0.0.0"
     
      ports:
        - 8001:8000
      depends_on:
        - db
    users-queue:
      build:
        context: ./users
        dockerfile: ./Dockerfile
      command: "php artisan queue:work"
     
      depends_on:
        - db

    notifications:
          build:
            context: ./notifications
            dockerfile: ./Dockerfile
          command: >
                  sh -c "php artisan serve --host=0.0.0.0"
         
          ports:
            - 8002:8000
          depends_on:
            - db
          
    notifications-queue:
          build:
            context: ./notifications
            dockerfile: ./Dockerfile
          command: "php artisan queue:work"
         
          depends_on:
            - db
    db:
      image: mysql:5.7.22
      environment:
        MYSQL_DATABASE: demo
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./users/storage/dbdata:/var/lib/mysql
      ports:
        - 33061:3306
      
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8183:80